export type ToolType = 'dashboard' | 'tracker' | 'manager' | 'monitor' | 'builder' | 'calendar' | 'inbox' | 'library' | 'reports' | 'system' | 'editor' | 'analytics'

export interface Tool {
  id: string
  name: string
  type: ToolType
  description: string
  status: 'active' | 'idle' | 'alert'
  metric?: string
  metricLabel?: string
  items?: { label: string; value: string; status?: 'good' | 'warn' | 'bad' }[]
}

export interface Workspace {
  id: string
  title: string
  role: string
  icon: string
  color: string
  description: string
  tools: Tool[]
}

export const workspaces: Workspace[] = [
  {
    id: 'operations',
    title: 'Operations Manager',
    role: 'Operations',
    icon: '◆',
    color: '#3b82f6',
    description: 'Oversees daily operations across all brands.',
    tools: [
      { id: 'ops-1', name: 'Global Operations Dashboard', type: 'dashboard', description: 'Live overview of orders, production, shipping, and team activity.', status: 'active', metric: '847', metricLabel: 'Active Orders', items: [{ label: 'Processing', value: '234', status: 'good' }, { label: 'Packing', value: '189', status: 'good' }, { label: 'Shipped', value: '412', status: 'good' }, { label: 'Delayed', value: '12', status: 'warn' }] },
      { id: 'ops-2', name: 'Order Fulfillment Monitor', type: 'tracker', description: 'Track order status from placed → packed → shipped.', status: 'active', metric: '96%', metricLabel: 'On-Time Rate', items: [{ label: 'Placed', value: '58' }, { label: 'Packed', value: '43' }, { label: 'Shipped', value: '412' }, { label: 'Delivered', value: '334' }] },
      { id: 'ops-3', name: 'Inventory Overview Panel', type: 'monitor', description: 'Real-time stock levels across all brands.', status: 'alert', metric: '12,480', metricLabel: 'Total Units', items: [{ label: 'District88', value: '4,200', status: 'good' }, { label: 'Divergent', value: '3,100', status: 'good' }, { label: 'Velvair', value: '2,800', status: 'warn' }, { label: 'Canjustalllove', value: '2,380', status: 'good' }] },
      { id: 'ops-4', name: 'Production Timeline Manager', type: 'calendar', description: 'Visualize product production deadlines.', status: 'active', metric: '6', metricLabel: 'Active Productions', items: [{ label: 'NOVA Drop', value: 'Apr 15' }, { label: 'PS2 Collection', value: 'Apr 30' }, { label: 'Spring Line', value: 'Mar 25' }, { label: 'D88 Merch', value: 'May 10' }] },
      { id: 'ops-5', name: 'Shipping Status Tracker', type: 'tracker', description: 'Monitor shipments and carrier updates.', status: 'active', metric: '412', metricLabel: 'In Transit', items: [{ label: 'USPS', value: '180', status: 'good' }, { label: 'UPS', value: '145', status: 'good' }, { label: 'FedEx', value: '67', status: 'good' }, { label: 'DHL', value: '20', status: 'warn' }] },
      { id: 'ops-6', name: 'Workflow Builder', type: 'builder', description: 'Create and adjust internal workflows for teams.', status: 'idle', metric: '8', metricLabel: 'Active Workflows', items: [{ label: 'Order Processing', value: 'Active' }, { label: 'Design Approval', value: 'Active' }, { label: 'Content Pipeline', value: 'Active' }, { label: 'Returns Flow', value: 'Draft' }] },
      { id: 'ops-7', name: 'Team Task Allocation Tool', type: 'manager', description: 'Assign tasks to fulfillment and production staff.', status: 'active', metric: '24', metricLabel: 'Unassigned Tasks', items: [{ label: 'Fulfillment', value: '12 tasks' }, { label: 'Production', value: '8 tasks' }, { label: 'Shipping', value: '4 tasks' }] },
      { id: 'ops-8', name: 'Deadline Alert System', type: 'system', description: 'Alerts when tasks or shipments risk delays.', status: 'alert', metric: '3', metricLabel: 'Active Alerts', items: [{ label: 'NOVA samples overdue', value: '2 days', status: 'bad' }, { label: 'PS2 fabric delivery', value: '1 day', status: 'warn' }, { label: 'Shipping batch #447', value: 'Today', status: 'warn' }] },
      { id: 'ops-9', name: 'Quality Compliance Tracker', type: 'tracker', description: 'Ensure processes meet quality standards.', status: 'active', metric: '98.2%', metricLabel: 'Compliance Rate', items: [{ label: 'Product Quality', value: '99%', status: 'good' }, { label: 'Packaging', value: '97%', status: 'good' }, { label: 'Shipping Accuracy', value: '98.5%', status: 'good' }] },
      { id: 'ops-10', name: 'Operations Calendar', type: 'calendar', description: 'Schedule logistics operations and deadlines.', status: 'active', metric: '18', metricLabel: 'Events This Month', items: [{ label: 'Mar 10 — Vendor call', value: '10:00 AM' }, { label: 'Mar 15 — Stock count', value: 'All day' }, { label: 'Mar 20 — Shipping audit', value: '2:00 PM' }] },
      { id: 'ops-11', name: 'Cross-Team Coordination Panel', type: 'manager', description: 'Coordinate work between marketing, design, and fulfillment.', status: 'active', metric: '5', metricLabel: 'Active Syncs', items: [{ label: 'Marketing ↔ Fulfillment', value: 'Synced' }, { label: 'Design ↔ Production', value: 'Synced' }, { label: 'Sales ↔ Inventory', value: 'Pending' }] },
      { id: 'ops-12', name: 'Supply Chain Tracker', type: 'tracker', description: 'Monitor materials and vendor deliveries.', status: 'active', metric: '14', metricLabel: 'Pending Deliveries', items: [{ label: 'Fabric — China', value: 'Mar 12', status: 'good' }, { label: 'Labels — Local', value: 'Mar 8', status: 'good' }, { label: 'Packaging — NYC', value: 'Mar 18', status: 'warn' }] },
      { id: 'ops-13', name: 'Operational Efficiency Metrics', type: 'analytics', description: 'Measure fulfillment speed and productivity.', status: 'active', metric: '4.2h', metricLabel: 'Avg Fulfillment Time', items: [{ label: 'Pack Time', value: '1.8h', status: 'good' }, { label: 'Ship Time', value: '2.4h', status: 'good' }, { label: 'Error Rate', value: '1.5%', status: 'good' }] },
      { id: 'ops-14', name: 'Issue Escalation System', type: 'system', description: 'Report and resolve operational problems quickly.', status: 'idle', metric: '2', metricLabel: 'Open Issues', items: [{ label: 'Printer malfunction', value: 'In Progress', status: 'warn' }, { label: 'Missing SKU labels', value: 'Resolved', status: 'good' }] },
      { id: 'ops-15', name: 'Operations Reporting Center', type: 'reports', description: 'Generate weekly operational reports.', status: 'active', metric: '12', metricLabel: 'Reports Generated', items: [{ label: 'Weekly Summary', value: 'Mar 3' }, { label: 'Monthly Overview', value: 'Feb 28' }, { label: 'Efficiency Report', value: 'Mar 1' }] },
    ],
  },
  {
    id: 'marketing',
    title: 'Marketing & Growth Manager',
    role: 'Marketing',
    icon: '◉',
    color: '#8b5cf6',
    description: 'Plans and executes marketing campaigns for brand growth.',
    tools: [
      { id: 'mkt-1', name: 'Campaign Command Dashboard', type: 'dashboard', description: 'Overview of all active marketing campaigns.', status: 'active', metric: '4', metricLabel: 'Active Campaigns', items: [{ label: 'NOVA Drop', value: 'Active', status: 'good' }, { label: 'Spring Love', value: 'Active', status: 'good' }, { label: 'D88 Launch', value: 'Draft' }, { label: 'PS2 Promo', value: 'Draft' }] },
      { id: 'mkt-2', name: 'Campaign Planner Tool', type: 'builder', description: 'Create launch timelines and campaign strategies.', status: 'active', metric: '3', metricLabel: 'Drafts in Progress', items: [{ label: 'Strategy', value: 'Define goals' }, { label: 'Timeline', value: 'Set milestones' }, { label: 'Assets', value: 'Assign creative' }] },
      { id: 'mkt-3', name: 'Ad Performance Tracker', type: 'analytics', description: 'Track results from ads across platforms.', status: 'active', metric: '$2.40', metricLabel: 'Avg CPC', items: [{ label: 'Instagram Ads', value: '$1.80 CPC', status: 'good' }, { label: 'Facebook Ads', value: '$2.90 CPC', status: 'warn' }, { label: 'TikTok Ads', value: '$2.50 CPC', status: 'good' }] },
      { id: 'mkt-4', name: 'Email Campaign Manager', type: 'manager', description: 'Design and schedule marketing emails.', status: 'active', metric: '24.8%', metricLabel: 'Open Rate', items: [{ label: 'NOVA Teaser', value: 'Sent — 28% open' }, { label: 'Spring Sale', value: 'Scheduled Mar 12' }, { label: 'Welcome Series', value: 'Active — 32% open' }] },
      { id: 'mkt-5', name: 'Conversion Analytics Dashboard', type: 'analytics', description: 'Monitor sales conversion rates.', status: 'active', metric: '3.8%', metricLabel: 'Conversion Rate', items: [{ label: 'Landing Pages', value: '4.2%', status: 'good' }, { label: 'Product Pages', value: '3.1%', status: 'good' }, { label: 'Cart → Purchase', value: '68%', status: 'good' }] },
      { id: 'mkt-6', name: 'A/B Testing Tool', type: 'builder', description: 'Test different ads or landing pages.', status: 'idle', metric: '2', metricLabel: 'Active Tests', items: [{ label: 'NOVA Hero Image', value: 'Running — 3 days' }, { label: 'CTA Button Color', value: 'Completed — Green won' }] },
      { id: 'mkt-7', name: 'Influencer Campaign Manager', type: 'manager', description: 'Manage influencer collaborations.', status: 'active', metric: '8', metricLabel: 'Active Partners', items: [{ label: 'Confirmed', value: '5 partners' }, { label: 'Pending', value: '3 outreach' }, { label: 'Content Received', value: '12 pieces' }] },
      { id: 'mkt-8', name: 'Marketing Budget Tracker', type: 'monitor', description: 'Monitor campaign spending.', status: 'active', metric: '$18.2K', metricLabel: 'Total Spent', items: [{ label: 'Ads', value: '$8,400', status: 'good' }, { label: 'Influencers', value: '$4,200', status: 'good' }, { label: 'Production', value: '$3,600', status: 'good' }, { label: 'Remaining', value: '$6,800', status: 'good' }] },
      { id: 'mkt-9', name: 'Audience Growth Tracker', type: 'analytics', description: 'Track brand follower and subscriber growth.', status: 'active', metric: '+2,340', metricLabel: 'New Followers (30d)', items: [{ label: 'Instagram', value: '+1,200', status: 'good' }, { label: 'TikTok', value: '+860', status: 'good' }, { label: 'Email List', value: '+280', status: 'good' }] },
      { id: 'mkt-10', name: 'Content Calendar Integration', type: 'calendar', description: 'Align marketing campaigns with content releases.', status: 'active', metric: '22', metricLabel: 'Scheduled Posts', items: [{ label: 'This Week', value: '8 posts' }, { label: 'Next Week', value: '6 posts' }, { label: 'Pending Approval', value: '4 posts' }] },
      { id: 'mkt-11', name: 'Promotion Code Manager', type: 'manager', description: 'Create and track discount campaigns.', status: 'active', metric: '6', metricLabel: 'Active Codes', items: [{ label: 'NOVA20', value: '142 uses', status: 'good' }, { label: 'SPRING15', value: '89 uses', status: 'good' }, { label: 'VIP30', value: '24 uses' }] },
      { id: 'mkt-12', name: 'Campaign Asset Library', type: 'library', description: 'Store marketing graphics and videos.', status: 'active', metric: '284', metricLabel: 'Total Assets', items: [{ label: 'Graphics', value: '142' }, { label: 'Videos', value: '38' }, { label: 'Copy Docs', value: '64' }, { label: 'Templates', value: '40' }] },
      { id: 'mkt-13', name: 'Growth Experiment Lab', type: 'builder', description: 'Test new marketing strategies.', status: 'idle', metric: '3', metricLabel: 'Experiments', items: [{ label: 'UGC Campaign Test', value: 'Running' }, { label: 'Referral Program', value: 'Planning' }, { label: 'SMS Marketing', value: 'Research' }] },
      { id: 'mkt-14', name: 'Traffic Source Analyzer', type: 'analytics', description: 'Identify where customers come from.', status: 'active', metric: '14.8K', metricLabel: 'Monthly Visitors', items: [{ label: 'Organic', value: '42%', status: 'good' }, { label: 'Social', value: '28%', status: 'good' }, { label: 'Paid', value: '18%', status: 'good' }, { label: 'Direct', value: '12%' }] },
      { id: 'mkt-15', name: 'Marketing Performance Reports', type: 'reports', description: 'Generate campaign success reports.', status: 'active', metric: '8', metricLabel: 'Reports This Month', items: [{ label: 'Campaign ROI', value: 'Mar 5' }, { label: 'Ad Performance', value: 'Mar 3' }, { label: 'Growth Summary', value: 'Feb 28' }] },
    ],
  },
  {
    id: 'customer',
    title: 'Customer Experience / Support Lead',
    role: 'Customer Service',
    icon: '◎',
    color: '#10b981',
    description: 'Manages customer inquiries, returns, and satisfaction.',
    tools: [
      { id: 'cx-1', name: 'Customer Support Inbox', type: 'inbox', description: 'Centralized message center for customer inquiries.', status: 'active', metric: '34', metricLabel: 'Unread Messages', items: [{ label: 'Email', value: '18 new', status: 'warn' }, { label: 'Instagram DM', value: '9 new' }, { label: 'Chat', value: '7 new' }] },
      { id: 'cx-2', name: 'Ticketing System', type: 'manager', description: 'Create and track customer support tickets.', status: 'active', metric: '47', metricLabel: 'Open Tickets', items: [{ label: 'New', value: '12', status: 'warn' }, { label: 'In Progress', value: '23', status: 'good' }, { label: 'Waiting', value: '8' }, { label: 'Resolved Today', value: '34', status: 'good' }] },
      { id: 'cx-3', name: 'Live Chat Support Panel', type: 'inbox', description: 'Respond to customer chat requests.', status: 'active', metric: '3', metricLabel: 'Active Chats', items: [{ label: 'Queue', value: '2 waiting' }, { label: 'Avg Wait', value: '45 sec', status: 'good' }, { label: 'Resolved Today', value: '28', status: 'good' }] },
      { id: 'cx-4', name: 'Customer Order Lookup Tool', type: 'manager', description: 'Quickly view order details.', status: 'active', metric: '∞', metricLabel: 'Search Ready', items: [{ label: 'By Order #', value: 'Search' }, { label: 'By Email', value: 'Search' }, { label: 'By Name', value: 'Search' }] },
      { id: 'cx-5', name: 'Return & Exchange Manager', type: 'manager', description: 'Manage product returns and exchanges.', status: 'active', metric: '8', metricLabel: 'Pending Returns', items: [{ label: 'Returns', value: '5 pending', status: 'warn' }, { label: 'Exchanges', value: '3 pending' }, { label: 'Processed Today', value: '6', status: 'good' }] },
      { id: 'cx-6', name: 'Customer Satisfaction Tracker', type: 'analytics', description: 'Monitor support ratings.', status: 'active', metric: '4.7/5', metricLabel: 'CSAT Score', items: [{ label: '5 Stars', value: '72%', status: 'good' }, { label: '4 Stars', value: '18%', status: 'good' }, { label: '3 Stars', value: '7%' }, { label: '1-2 Stars', value: '3%', status: 'warn' }] },
      { id: 'cx-7', name: 'Complaint Resolution Tracker', type: 'tracker', description: 'Track how issues are resolved.', status: 'active', metric: '94%', metricLabel: 'Resolution Rate', items: [{ label: 'Avg Resolution Time', value: '4.2 hours', status: 'good' }, { label: 'First Contact Resolution', value: '78%', status: 'good' }, { label: 'Escalated', value: '6%' }] },
      { id: 'cx-8', name: 'Customer Feedback Dashboard', type: 'analytics', description: 'Collect and analyze feedback.', status: 'active', metric: '156', metricLabel: 'Reviews This Month', items: [{ label: 'Product Quality', value: '4.8/5', status: 'good' }, { label: 'Shipping Speed', value: '4.3/5', status: 'good' }, { label: 'Packaging', value: '4.6/5', status: 'good' }] },
      { id: 'cx-9', name: 'Support Knowledge Base', type: 'library', description: 'Quick access to help articles.', status: 'active', metric: '48', metricLabel: 'Articles', items: [{ label: 'Shipping FAQ', value: '12 articles' }, { label: 'Returns Policy', value: '8 articles' }, { label: 'Product Care', value: '14 articles' }, { label: 'Account Help', value: '14 articles' }] },
      { id: 'cx-10', name: 'Customer Loyalty Tracker', type: 'analytics', description: 'Identify repeat customers.', status: 'active', metric: '38%', metricLabel: 'Repeat Rate', items: [{ label: 'VIP Customers', value: '124', status: 'good' }, { label: 'Repeat Buyers', value: '482', status: 'good' }, { label: 'First-Time', value: '786' }] },
      { id: 'cx-11', name: 'Support Response Time Monitor', type: 'monitor', description: 'Track response speed.', status: 'active', metric: '12m', metricLabel: 'Avg Response', items: [{ label: 'Email', value: '28 min', status: 'good' }, { label: 'Chat', value: '45 sec', status: 'good' }, { label: 'Social', value: '2.1 hrs', status: 'warn' }] },
      { id: 'cx-12', name: 'Customer Profile Viewer', type: 'manager', description: 'View purchase history and interactions.', status: 'active', metric: '2,840', metricLabel: 'Total Customers', items: [{ label: 'Active (30d)', value: '680', status: 'good' }, { label: 'At Risk', value: '42', status: 'warn' }, { label: 'New This Month', value: '124', status: 'good' }] },
      { id: 'cx-13', name: 'Support Analytics Dashboard', type: 'analytics', description: 'See common issues and trends.', status: 'active', metric: '5', metricLabel: 'Top Issues', items: [{ label: 'Shipping Delays', value: '24%', status: 'warn' }, { label: 'Sizing Questions', value: '20%' }, { label: 'Order Status', value: '18%' }, { label: 'Returns', value: '15%' }] },
      { id: 'cx-14', name: 'Priority Case Flagging System', type: 'system', description: 'Escalate urgent issues.', status: 'alert', metric: '2', metricLabel: 'Flagged Cases', items: [{ label: 'Lost package — VIP', value: 'Urgent', status: 'bad' }, { label: 'Damaged item — Influencer', value: 'High', status: 'warn' }] },
      { id: 'cx-15', name: 'Customer Experience Reports', type: 'reports', description: 'Generate insights on satisfaction.', status: 'active', metric: '6', metricLabel: 'Reports Available', items: [{ label: 'Monthly CSAT', value: 'Mar 1' }, { label: 'NPS Report', value: 'Feb 28' }, { label: 'Issue Trends', value: 'Mar 3' }] },
    ],
  },
  {
    id: 'content',
    title: 'Content Creator / Media Specialist',
    role: 'Creative',
    icon: '✦',
    color: '#ec4899',
    description: 'Produces photography, video, and graphics for all brands.',
    tools: [
      { id: 'cnt-1', name: 'Media Production Dashboard', type: 'dashboard', description: 'Overview of active content projects.', status: 'active', metric: '12', metricLabel: 'Active Projects', items: [{ label: 'Photography', value: '4 projects' }, { label: 'Video', value: '3 projects' }, { label: 'Graphics', value: '5 projects' }] },
      { id: 'cnt-2', name: 'Content Upload Studio', type: 'builder', description: 'Upload photos, videos, and graphics.', status: 'active', metric: '38', metricLabel: 'Uploads This Week', items: [{ label: 'Photos', value: '22 uploaded' }, { label: 'Videos', value: '4 uploaded' }, { label: 'Graphics', value: '12 uploaded' }] },
      { id: 'cnt-3', name: 'Content Editing Workspace', type: 'editor', description: 'Review and edit media files.', status: 'active', metric: '6', metricLabel: 'In Editing', items: [{ label: 'NOVA Lookbook', value: 'Editing', status: 'good' }, { label: 'PS2 Promo Video', value: 'Review' }, { label: 'Spring Banners', value: 'Draft' }] },
      { id: 'cnt-4', name: 'Creative Brief Manager', type: 'manager', description: 'View instructions for content projects.', status: 'active', metric: '8', metricLabel: 'Active Briefs', items: [{ label: 'NOVA Campaign', value: 'In Progress' }, { label: 'Spring Social', value: 'Assigned' }, { label: 'D88 Launch', value: 'Pending' }] },
      { id: 'cnt-5', name: 'Brand Style Guide Panel', type: 'library', description: 'Ensure visuals follow brand rules.', status: 'active', metric: '5', metricLabel: 'Brand Guides', items: [{ label: 'Divergent Studios', value: 'Updated' }, { label: 'District88', value: 'Updated' }, { label: 'Velvair Studios', value: 'Updated' }, { label: 'Canjustalllove', value: 'Updated' }] },
      { id: 'cnt-6', name: 'Content Approval System', type: 'system', description: 'Submit media for approval.', status: 'active', metric: '4', metricLabel: 'Pending Approval', items: [{ label: 'NOVA Hero Image', value: 'Submitted', status: 'warn' }, { label: 'Spring Reel #3', value: 'Submitted' }, { label: 'D88 Icon Set', value: 'Approved', status: 'good' }] },
      { id: 'cnt-7', name: 'Asset Tagging System', type: 'manager', description: 'Organize content by campaign or brand.', status: 'active', metric: '1,240', metricLabel: 'Tagged Assets', items: [{ label: 'By Brand', value: '5 categories' }, { label: 'By Campaign', value: '8 categories' }, { label: 'By Type', value: '6 categories' }] },
      { id: 'cnt-8', name: 'Video Project Manager', type: 'tracker', description: 'Track editing progress.', status: 'active', metric: '3', metricLabel: 'In Production', items: [{ label: 'PS2 Promo', value: '60% edited', status: 'good' }, { label: 'NOVA Behind-Scenes', value: '30%' }, { label: 'Brand Story', value: 'Pre-production' }] },
      { id: 'cnt-9', name: 'Photo Shoot Integration', type: 'calendar', description: 'Connect shoots with media production.', status: 'active', metric: '2', metricLabel: 'Upcoming Shoots', items: [{ label: 'NOVA Editorial', value: 'Mar 25' }, { label: 'PS2 Street Shoot', value: 'Apr 5' }] },
      { id: 'cnt-10', name: 'Social Content Export Tool', type: 'builder', description: 'Format content for platforms.', status: 'active', metric: '5', metricLabel: 'Export Formats', items: [{ label: 'Instagram', value: '1080×1080' }, { label: 'TikTok', value: '1080×1920' }, { label: 'Twitter/X', value: '1200×675' }, { label: 'Web Banner', value: '1920×600' }] },
      { id: 'cnt-11', name: 'Creative Version History', type: 'tracker', description: 'Track revisions of designs.', status: 'active', metric: '48', metricLabel: 'Versions Tracked', items: [{ label: 'NOVA Key Visual', value: 'v3 — Latest' }, { label: 'D88 App Icon', value: 'v5 — Approved' }, { label: 'Spring Banner', value: 'v1 — Draft' }] },
      { id: 'cnt-12', name: 'Media Storage Library', type: 'library', description: 'Access company media vault.', status: 'active', metric: '4.2 GB', metricLabel: 'Total Storage', items: [{ label: 'Photos', value: '1.8 GB' }, { label: 'Videos', value: '1.6 GB' }, { label: 'Graphics', value: '0.6 GB' }, { label: 'Documents', value: '0.2 GB' }] },
      { id: 'cnt-13', name: 'Content Performance Dashboard', type: 'analytics', description: 'Track engagement metrics.', status: 'active', metric: '12.4K', metricLabel: 'Total Engagement', items: [{ label: 'Likes', value: '8,200', status: 'good' }, { label: 'Comments', value: '1,840', status: 'good' }, { label: 'Shares', value: '2,360', status: 'good' }] },
      { id: 'cnt-14', name: 'Creative Collaboration Panel', type: 'inbox', description: 'Receive feedback from team.', status: 'active', metric: '6', metricLabel: 'Feedback Threads', items: [{ label: 'NOVA Lookbook', value: '3 comments' }, { label: 'PS2 Video Cut', value: '2 comments' }, { label: 'Spring Assets', value: '1 comment' }] },
      { id: 'cnt-15', name: 'Content Scheduling Integration', type: 'calendar', description: 'Send media to social calendar.', status: 'active', metric: '14', metricLabel: 'Queued for Post', items: [{ label: 'Today', value: '3 posts' }, { label: 'Tomorrow', value: '2 posts' }, { label: 'This Week', value: '9 posts' }] },
    ],
  },
  {
    id: 'sales',
    title: 'Sales & Outreach Coordinator',
    role: 'Sales',
    icon: '◈',
    color: '#f59e0b',
    description: 'Manages direct sales, partnerships, and outreach.',
    tools: [
      { id: 'sal-1', name: 'Lead Management Dashboard', type: 'dashboard', description: 'Track potential customers and partners.', status: 'active', metric: '142', metricLabel: 'Active Leads', items: [{ label: 'Hot', value: '18', status: 'good' }, { label: 'Warm', value: '54' }, { label: 'Cold', value: '70' }] },
      { id: 'sal-2', name: 'CRM System', type: 'manager', description: 'Store contact details and communication history.', status: 'active', metric: '580', metricLabel: 'Total Contacts', items: [{ label: 'Partners', value: '42' }, { label: 'Influencers', value: '86' }, { label: 'Wholesale', value: '28' }, { label: 'Leads', value: '424' }] },
      { id: 'sal-3', name: 'Influencer Partnership Tracker', type: 'tracker', description: 'Manage collaborations.', status: 'active', metric: '12', metricLabel: 'Active Partnerships', items: [{ label: 'Contracted', value: '8', status: 'good' }, { label: 'Negotiating', value: '4', status: 'warn' }, { label: 'Content Received', value: '24 pieces' }] },
      { id: 'sal-4', name: 'Wholesale Partner Database', type: 'manager', description: 'Track retail partners.', status: 'active', metric: '16', metricLabel: 'Retail Partners', items: [{ label: 'Active', value: '12', status: 'good' }, { label: 'Pending', value: '4' }, { label: 'Revenue (MTD)', value: '$14,200' }] },
      { id: 'sal-5', name: 'Outreach Campaign Manager', type: 'manager', description: 'Organize outreach efforts.', status: 'active', metric: '3', metricLabel: 'Active Campaigns', items: [{ label: 'Influencer Outreach', value: '42 sent' }, { label: 'Wholesale Pitch', value: '18 sent' }, { label: 'Collab Invites', value: '24 sent' }] },
      { id: 'sal-6', name: 'Sales Pipeline Tracker', type: 'tracker', description: 'Visualize sales stages.', status: 'active', metric: '$42K', metricLabel: 'Pipeline Value', items: [{ label: 'Prospect', value: '$12K' }, { label: 'Contacted', value: '$8K' }, { label: 'Proposal', value: '$14K', status: 'good' }, { label: 'Closing', value: '$8K', status: 'good' }] },
      { id: 'sal-7', name: 'Follow-Up Reminder System', type: 'system', description: 'Remind staff to follow up with leads.', status: 'alert', metric: '7', metricLabel: 'Due Today', items: [{ label: 'Retailer — NYC Store', value: 'Overdue', status: 'bad' }, { label: 'Influencer — @styleking', value: 'Today', status: 'warn' }, { label: 'Wholesale — West Coast', value: 'Tomorrow' }] },
      { id: 'sal-8', name: 'Deal Tracking Panel', type: 'tracker', description: 'Track ongoing negotiations.', status: 'active', metric: '5', metricLabel: 'Open Deals', items: [{ label: 'NYC Pop-up', value: '$8K — Negotiating', status: 'good' }, { label: 'Online Retailer', value: '$12K — Proposal' }, { label: 'Event Sponsorship', value: '$3K — Review' }] },
      { id: 'sal-9', name: 'Partnership Agreement Storage', type: 'library', description: 'Store collaboration contracts.', status: 'active', metric: '24', metricLabel: 'Documents', items: [{ label: 'Active Contracts', value: '12' }, { label: 'Expired', value: '8' }, { label: 'Drafts', value: '4' }] },
      { id: 'sal-10', name: 'Outreach Analytics Dashboard', type: 'analytics', description: 'Track conversion rates.', status: 'active', metric: '18%', metricLabel: 'Response Rate', items: [{ label: 'Email Open Rate', value: '42%', status: 'good' }, { label: 'Response Rate', value: '18%', status: 'good' }, { label: 'Conversion', value: '6%' }] },
      { id: 'sal-11', name: 'Contact Activity Timeline', type: 'tracker', description: 'Record communications with partners.', status: 'active', metric: '86', metricLabel: 'Activities (30d)', items: [{ label: 'Emails Sent', value: '48' }, { label: 'Calls Made', value: '22' }, { label: 'Meetings', value: '16' }] },
      { id: 'sal-12', name: 'Proposal Builder Tool', type: 'builder', description: 'Create partnership proposals.', status: 'idle', metric: '3', metricLabel: 'Templates', items: [{ label: 'Wholesale Pitch', value: 'Template' }, { label: 'Collab Proposal', value: 'Template' }, { label: 'Sponsorship Deck', value: 'Template' }] },
      { id: 'sal-13', name: 'Affiliate Program Manager', type: 'manager', description: 'Track affiliate partners.', status: 'active', metric: '28', metricLabel: 'Affiliates', items: [{ label: 'Active', value: '22', status: 'good' }, { label: 'Revenue Generated', value: '$4,800' }, { label: 'Avg Commission', value: '12%' }] },
      { id: 'sal-14', name: 'Sales Opportunity Alerts', type: 'system', description: 'Notify when new leads appear.', status: 'active', metric: '4', metricLabel: 'New Opportunities', items: [{ label: 'Boutique inquiry', value: 'New', status: 'good' }, { label: 'Brand collab request', value: 'New', status: 'good' }, { label: 'Pop-up event invite', value: '2 days ago' }] },
      { id: 'sal-15', name: 'Sales Performance Reports', type: 'reports', description: 'Measure outreach success.', status: 'active', metric: '4', metricLabel: 'Reports Available', items: [{ label: 'Monthly Revenue', value: 'Mar 1' }, { label: 'Pipeline Analysis', value: 'Feb 28' }, { label: 'Partner ROI', value: 'Mar 3' }] },
    ],
  },
  {
    id: 'fulfillment',
    title: 'Order Fulfillment / Warehouse Associate',
    role: 'Fulfillment',
    icon: '▣',
    color: '#06b6d4',
    description: 'Picks, packs, and ships customer orders.',
    tools: [
      { id: 'ful-1', name: 'Order Packing Dashboard', type: 'dashboard', description: 'View orders ready for packing.', status: 'active', metric: '43', metricLabel: 'Ready to Pack', items: [{ label: 'Priority', value: '8 orders', status: 'warn' }, { label: 'Standard', value: '28 orders' }, { label: 'Bulk', value: '7 orders' }] },
      { id: 'ful-2', name: 'Pick List Generator', type: 'builder', description: 'Show items needed for each order.', status: 'active', metric: '43', metricLabel: 'Lists Generated', items: [{ label: 'Single Item', value: '22 orders' }, { label: 'Multi Item', value: '18 orders' }, { label: 'Custom Bundle', value: '3 orders' }] },
      { id: 'ful-3', name: 'Barcode Scanner Integration', type: 'system', description: 'Verify products quickly.', status: 'active', metric: '✓', metricLabel: 'Scanner Ready', items: [{ label: 'Scanned Today', value: '186 items', status: 'good' }, { label: 'Errors Caught', value: '2', status: 'good' }, { label: 'Accuracy', value: '99.8%', status: 'good' }] },
      { id: 'ful-4', name: 'Shipping Label Generator', type: 'builder', description: 'Create shipping labels.', status: 'active', metric: '38', metricLabel: 'Labels Today', items: [{ label: 'USPS', value: '18 labels' }, { label: 'UPS', value: '12 labels' }, { label: 'FedEx', value: '8 labels' }] },
      { id: 'ful-5', name: 'Packing Checklist Tool', type: 'tracker', description: 'Ensure correct items are packed.', status: 'active', metric: '100%', metricLabel: 'Accuracy Target', items: [{ label: 'Items Verified', value: '186', status: 'good' }, { label: 'Packaging Check', value: '38', status: 'good' }, { label: 'Insert Cards', value: '38', status: 'good' }] },
      { id: 'ful-6', name: 'Shipment Tracking Panel', type: 'tracker', description: 'Monitor shipped packages.', status: 'active', metric: '412', metricLabel: 'In Transit', items: [{ label: 'On Time', value: '398', status: 'good' }, { label: 'Delayed', value: '10', status: 'warn' }, { label: 'Exception', value: '4', status: 'bad' }] },
      { id: 'ful-7', name: 'Inventory Update Tool', type: 'editor', description: 'Adjust stock after packing.', status: 'active', metric: '186', metricLabel: 'Updated Today', items: [{ label: 'Decremented', value: '186 items' }, { label: 'Low Stock Flags', value: '4 SKUs', status: 'warn' }, { label: 'Out of Stock', value: '1 SKU', status: 'bad' }] },
      { id: 'ful-8', name: 'Warehouse Map System', type: 'manager', description: 'Locate items in storage quickly.', status: 'active', metric: '12', metricLabel: 'Zones Active', items: [{ label: 'Zone A — Apparel', value: '4 racks' }, { label: 'Zone B — Accessories', value: '2 racks' }, { label: 'Zone C — Shipping', value: '3 stations' }] },
      { id: 'ful-9', name: 'Bulk Order Processing Tool', type: 'manager', description: 'Handle large batches of orders.', status: 'idle', metric: '2', metricLabel: 'Bulk Batches', items: [{ label: 'Wholesale — NYC', value: '48 units' }, { label: 'Event Orders', value: '24 units' }] },
      { id: 'ful-10', name: 'Fulfillment Speed Tracker', type: 'analytics', description: 'Measure packing efficiency.', status: 'active', metric: '8.4m', metricLabel: 'Avg Pack Time', items: [{ label: 'Single Item', value: '4.2 min', status: 'good' }, { label: 'Multi Item', value: '12.6 min', status: 'good' }, { label: 'Goal', value: '< 10 min' }] },
      { id: 'ful-11', name: 'Shipping Error Reporting Tool', type: 'system', description: 'Report order issues.', status: 'idle', metric: '2', metricLabel: 'Reports Today', items: [{ label: 'Wrong item packed', value: 'Resolved', status: 'good' }, { label: 'Address issue', value: 'In Progress', status: 'warn' }] },
      { id: 'ful-12', name: 'Carrier Integration Panel', type: 'manager', description: 'Connect with shipping carriers.', status: 'active', metric: '4', metricLabel: 'Carriers Active', items: [{ label: 'USPS', value: 'Connected', status: 'good' }, { label: 'UPS', value: 'Connected', status: 'good' }, { label: 'FedEx', value: 'Connected', status: 'good' }, { label: 'DHL', value: 'Connected', status: 'good' }] },
      { id: 'ful-13', name: 'Stock Reorder Alerts', type: 'system', description: 'Notify when items run low.', status: 'alert', metric: '4', metricLabel: 'Low Stock', items: [{ label: 'NOVA Hoodie — M', value: '3 left', status: 'bad' }, { label: 'D88 Tee — L', value: '8 left', status: 'warn' }, { label: 'Velvair Cap', value: '5 left', status: 'warn' }] },
      { id: 'ful-14', name: 'Daily Fulfillment Summary', type: 'reports', description: 'Review completed orders.', status: 'active', metric: '38', metricLabel: 'Shipped Today', items: [{ label: 'Total Packed', value: '38' }, { label: 'Total Shipped', value: '36' }, { label: 'Pending', value: '2' }] },
      { id: 'ful-15', name: 'Warehouse Task Board', type: 'manager', description: 'Assign fulfillment tasks.', status: 'active', metric: '6', metricLabel: 'Active Tasks', items: [{ label: 'Restock Zone A', value: 'Assigned' }, { label: 'Label Batch #12', value: 'In Progress', status: 'good' }, { label: 'Inventory Count', value: 'Scheduled' }] },
    ],
  },
  {
    id: 'ecommerce',
    title: 'E-commerce / Website Support',
    role: 'Technology',
    icon: '▤',
    color: '#6366f1',
    description: 'Manages online stores and website functionality.',
    tools: [
      { id: 'eco-1', name: 'Product Management Dashboard', type: 'dashboard', description: 'Manage store listings.', status: 'active', metric: '248', metricLabel: 'Total Products', items: [{ label: 'Active', value: '186', status: 'good' }, { label: 'Draft', value: '42' }, { label: 'Out of Stock', value: '12', status: 'warn' }, { label: 'Hidden', value: '8' }] },
      { id: 'eco-2', name: 'Product Upload Tool', type: 'builder', description: 'Add new items quickly.', status: 'active', metric: '6', metricLabel: 'Pending Upload', items: [{ label: 'NOVA Collection', value: '4 items' }, { label: 'Accessories', value: '2 items' }] },
      { id: 'eco-3', name: 'Pricing & Discount Editor', type: 'editor', description: 'Update pricing and promotions.', status: 'active', metric: '6', metricLabel: 'Active Discounts', items: [{ label: 'NOVA20', value: '20% off', status: 'good' }, { label: 'SPRING15', value: '15% off', status: 'good' }, { label: 'VIP30', value: '30% off' }] },
      { id: 'eco-4', name: 'Site Health Monitor', type: 'monitor', description: 'Detect technical problems.', status: 'active', metric: '99.8%', metricLabel: 'Uptime', items: [{ label: 'Response Time', value: '240ms', status: 'good' }, { label: 'Error Rate', value: '0.2%', status: 'good' }, { label: 'Last Incident', value: '14 days ago' }] },
      { id: 'eco-5', name: 'Checkout Performance Tracker', type: 'analytics', description: 'Monitor checkout success rates.', status: 'active', metric: '92%', metricLabel: 'Completion Rate', items: [{ label: 'Cart → Checkout', value: '78%', status: 'good' }, { label: 'Payment Success', value: '96%', status: 'good' }, { label: 'Abandoned Carts', value: '22%', status: 'warn' }] },
      { id: 'eco-6', name: 'Bug Reporting System', type: 'system', description: 'Report site errors to developers.', status: 'idle', metric: '3', metricLabel: 'Open Bugs', items: [{ label: 'Mobile menu glitch', value: 'In Progress', status: 'warn' }, { label: 'Image load delay', value: 'Assigned' }, { label: 'Cart counter bug', value: 'New' }] },
      { id: 'eco-7', name: 'UX Feedback Panel', type: 'inbox', description: 'Collect usability feedback.', status: 'active', metric: '18', metricLabel: 'Feedback Items', items: [{ label: 'Navigation', value: '6 reports' }, { label: 'Checkout', value: '5 reports' }, { label: 'Search', value: '4 reports' }, { label: 'Mobile', value: '3 reports' }] },
      { id: 'eco-8', name: 'Product Analytics Dashboard', type: 'analytics', description: 'See product performance.', status: 'active', metric: '1,240', metricLabel: 'Views This Week', items: [{ label: 'Top Product', value: 'NOVA Hoodie — 340 views' }, { label: 'Highest Convert', value: 'D88 Tee — 8.2%' }, { label: 'Most Added to Cart', value: 'Velvair Cap — 186' }] },
      { id: 'eco-9', name: 'Inventory Sync Tool', type: 'system', description: 'Sync stock levels with stores.', status: 'active', metric: '✓', metricLabel: 'All Synced', items: [{ label: 'Main Store', value: 'Synced', status: 'good' }, { label: 'District88', value: 'Synced', status: 'good' }, { label: 'Wholesale Portal', value: 'Synced', status: 'good' }] },
      { id: 'eco-10', name: 'Landing Page Builder', type: 'builder', description: 'Create promotional pages.', status: 'active', metric: '4', metricLabel: 'Active Pages', items: [{ label: 'NOVA Launch', value: 'Live', status: 'good' }, { label: 'Spring Sale', value: 'Draft' }, { label: 'D88 Beta', value: 'Scheduled' }] },
      { id: 'eco-11', name: 'Website Content Editor', type: 'editor', description: 'Update site text and visuals.', status: 'active', metric: '12', metricLabel: 'Recent Edits', items: [{ label: 'Homepage Hero', value: 'Updated today' }, { label: 'About Page', value: '3 days ago' }, { label: 'Product Descriptions', value: '1 week ago' }] },
      { id: 'eco-12', name: 'Mobile Optimization Checker', type: 'monitor', description: 'Ensure mobile compatibility.', status: 'active', metric: '94', metricLabel: 'Mobile Score', items: [{ label: 'Performance', value: '92/100', status: 'good' }, { label: 'Accessibility', value: '96/100', status: 'good' }, { label: 'SEO', value: '94/100', status: 'good' }] },
      { id: 'eco-13', name: 'Search Optimization Panel', type: 'analytics', description: 'Manage product SEO settings.', status: 'active', metric: '86', metricLabel: 'SEO Score', items: [{ label: 'Indexed Pages', value: '124', status: 'good' }, { label: 'Top Keywords', value: '18 ranking' }, { label: 'Backlinks', value: '42' }] },
      { id: 'eco-14', name: 'Customer Behavior Analytics', type: 'analytics', description: 'Track site navigation.', status: 'active', metric: '3.2m', metricLabel: 'Avg Session', items: [{ label: 'Pages/Session', value: '4.8', status: 'good' }, { label: 'Bounce Rate', value: '32%', status: 'good' }, { label: 'Top Exit Page', value: 'Cart' }] },
      { id: 'eco-15', name: 'Site Performance Reports', type: 'reports', description: 'Generate website insights.', status: 'active', metric: '6', metricLabel: 'Reports Available', items: [{ label: 'Weekly Traffic', value: 'Mar 3' }, { label: 'Conversion Report', value: 'Mar 1' }, { label: 'Error Log', value: 'Mar 5' }] },
    ],
  },
  {
    id: 'social',
    title: 'Social Media Manager',
    role: 'Marketing',
    icon: '◐',
    color: '#f43f5e',
    description: 'Manages social media presence across all platforms.',
    tools: [
      { id: 'soc-1', name: 'Social Media Dashboard', type: 'dashboard', description: 'Overview of all accounts.', status: 'active', metric: '28.4K', metricLabel: 'Total Followers', items: [{ label: 'Instagram', value: '14,200', status: 'good' }, { label: 'TikTok', value: '8,600', status: 'good' }, { label: 'Twitter/X', value: '3,400' }, { label: 'Facebook', value: '2,200' }] },
      { id: 'soc-2', name: 'Post Scheduler', type: 'calendar', description: 'Plan and schedule posts.', status: 'active', metric: '22', metricLabel: 'Scheduled Posts', items: [{ label: 'Today', value: '3 posts' }, { label: 'This Week', value: '12 posts' }, { label: 'Next Week', value: '7 posts' }] },
      { id: 'soc-3', name: 'Content Calendar', type: 'calendar', description: 'Visualize upcoming posts.', status: 'active', metric: '45', metricLabel: 'Posts This Month', items: [{ label: 'Published', value: '18', status: 'good' }, { label: 'Scheduled', value: '22' }, { label: 'Draft', value: '5' }] },
      { id: 'soc-4', name: 'Engagement Tracker', type: 'analytics', description: 'Track likes, comments, and shares.', status: 'active', metric: '4.8%', metricLabel: 'Engagement Rate', items: [{ label: 'Likes (7d)', value: '3,420', status: 'good' }, { label: 'Comments', value: '486', status: 'good' }, { label: 'Shares', value: '892', status: 'good' }, { label: 'Saves', value: '1,240', status: 'good' }] },
      { id: 'soc-5', name: 'Follower Growth Monitor', type: 'analytics', description: 'Measure audience growth.', status: 'active', metric: '+840', metricLabel: 'New (7 Days)', items: [{ label: 'Instagram', value: '+420', status: 'good' }, { label: 'TikTok', value: '+280', status: 'good' }, { label: 'Twitter/X', value: '+90' }, { label: 'Facebook', value: '+50' }] },
      { id: 'soc-6', name: 'Trend Discovery Tool', type: 'monitor', description: 'Track trending topics.', status: 'active', metric: '12', metricLabel: 'Trending Topics', items: [{ label: '#streetwear2026', value: 'Trending', status: 'good' }, { label: '#sneakerculture', value: 'Rising' }, { label: '#springfashion', value: 'Peak' }] },
      { id: 'soc-7', name: 'Comment & Message Inbox', type: 'inbox', description: 'Respond to followers.', status: 'active', metric: '24', metricLabel: 'Unread', items: [{ label: 'Instagram DMs', value: '12', status: 'warn' }, { label: 'Comments', value: '8' }, { label: 'TikTok', value: '4' }] },
      { id: 'soc-8', name: 'Hashtag Performance Tracker', type: 'analytics', description: 'Analyze hashtag results.', status: 'active', metric: '18', metricLabel: 'Active Hashtags', items: [{ label: '#WilsonCollective', value: '2.4K reach', status: 'good' }, { label: '#District88', value: '1.8K reach' }, { label: '#NOVADrop', value: '3.2K reach', status: 'good' }] },
      { id: 'soc-9', name: 'Platform Analytics Dashboard', type: 'analytics', description: 'Track performance across platforms.', status: 'active', metric: '48K', metricLabel: 'Monthly Reach', items: [{ label: 'Instagram', value: '22K reach', status: 'good' }, { label: 'TikTok', value: '18K reach', status: 'good' }, { label: 'Twitter/X', value: '5K reach' }, { label: 'Facebook', value: '3K reach' }] },
      { id: 'soc-10', name: 'Post Approval System', type: 'system', description: 'Get marketing approval before publishing.', status: 'active', metric: '3', metricLabel: 'Pending Approval', items: [{ label: 'NOVA Teaser Reel', value: 'Pending', status: 'warn' }, { label: 'Spring Story Set', value: 'Pending' }, { label: 'D88 Announcement', value: 'Approved', status: 'good' }] },
      { id: 'soc-11', name: 'Social Campaign Integration', type: 'manager', description: 'Connect with marketing campaigns.', status: 'active', metric: '4', metricLabel: 'Linked Campaigns', items: [{ label: 'NOVA Drop', value: 'Active', status: 'good' }, { label: 'Spring Love', value: 'Active', status: 'good' }, { label: 'D88 Launch', value: 'Upcoming' }] },
      { id: 'soc-12', name: 'Brand Voice Guide Panel', type: 'library', description: 'Maintain consistent messaging.', status: 'active', metric: '5', metricLabel: 'Brand Guides', items: [{ label: 'Divergent', value: 'Bold, futuristic' }, { label: 'Velvair', value: 'Edgy, urban' }, { label: 'Canjustalllove', value: 'Warm, inclusive' }] },
      { id: 'soc-13', name: 'Content Collaboration Tool', type: 'inbox', description: 'Work with content creators.', status: 'active', metric: '4', metricLabel: 'Active Collabs', items: [{ label: 'Review requests', value: '2 pending' }, { label: 'Feedback given', value: '6 threads' }] },
      { id: 'soc-14', name: 'Viral Content Alerts', type: 'system', description: 'Detect high-performing posts.', status: 'active', metric: '1', metricLabel: 'Viral Alert', items: [{ label: 'NOVA Teaser', value: '12K views in 2hrs', status: 'good' }] },
      { id: 'soc-15', name: 'Social Media Reports', type: 'reports', description: 'Generate growth insights.', status: 'active', metric: '8', metricLabel: 'Reports Available', items: [{ label: 'Weekly Growth', value: 'Mar 5' }, { label: 'Engagement Report', value: 'Mar 3' }, { label: 'Platform Comparison', value: 'Mar 1' }] },
    ],
  },
  {
    id: 'quality',
    title: 'Packaging & Quality Control',
    role: 'Quality',
    icon: '◬',
    color: '#14b8a6',
    description: 'Inspects products and manages packaging standards.',
    tools: [
      { id: 'qc-1', name: 'Quality Inspection Dashboard', type: 'dashboard', description: 'Review items before shipment.', status: 'active', metric: '186', metricLabel: 'Inspected Today', items: [{ label: 'Passed', value: '182', status: 'good' }, { label: 'Failed', value: '4', status: 'bad' }, { label: 'Pass Rate', value: '97.8%', status: 'good' }] },
      { id: 'qc-2', name: 'Product Inspection Checklist', type: 'tracker', description: 'Ensure product quality.', status: 'active', metric: '8', metricLabel: 'Checklist Items', items: [{ label: 'Stitching', value: 'Check' }, { label: 'Print Quality', value: 'Check' }, { label: 'Fabric', value: 'Check' }, { label: 'Labels', value: 'Check' }] },
      { id: 'qc-3', name: 'Packaging Instruction Panel', type: 'library', description: 'Show brand packaging standards.', status: 'active', metric: '5', metricLabel: 'Brand Standards', items: [{ label: 'Divergent', value: 'Black tissue + sticker' }, { label: 'Velvair', value: 'Custom box + card' }, { label: 'Canjustalllove', value: 'Pink wrap + tag' }] },
      { id: 'qc-4', name: 'Order Accuracy Verification Tool', type: 'tracker', description: 'Confirm items before packing.', status: 'active', metric: '99.5%', metricLabel: 'Accuracy Rate', items: [{ label: 'Correct Items', value: '184/186', status: 'good' }, { label: 'Correct Qty', value: '186/186', status: 'good' }, { label: 'Correct Size', value: '185/186', status: 'good' }] },
      { id: 'qc-5', name: 'Quality Issue Reporting Tool', type: 'system', description: 'Flag defective products.', status: 'active', metric: '4', metricLabel: 'Issues Today', items: [{ label: 'Misprint — NOVA Tee', value: 'Flagged', status: 'bad' }, { label: 'Loose stitch — Hoodie', value: 'Flagged', status: 'warn' }, { label: 'Wrong label', value: 'Fixed', status: 'good' }] },
      { id: 'qc-6', name: 'Packaging Supply Tracker', type: 'monitor', description: 'Track packing material inventory.', status: 'active', metric: '2', metricLabel: 'Low Stock Items', items: [{ label: 'Poly Mailers (M)', value: '240 left', status: 'good' }, { label: 'Custom Boxes', value: '45 left', status: 'warn' }, { label: 'Tissue Paper', value: '180 left', status: 'good' }, { label: 'Stickers', value: '320 left', status: 'good' }] },
      { id: 'qc-7', name: 'Packaging Efficiency Monitor', type: 'analytics', description: 'Track packing speed.', status: 'active', metric: '5.2m', metricLabel: 'Avg Pack Time', items: [{ label: 'Standard', value: '4.2 min', status: 'good' }, { label: 'Premium', value: '6.8 min', status: 'good' }, { label: 'Bulk', value: '3.1 min', status: 'good' }] },
      { id: 'qc-8', name: 'Damage Reporting System', type: 'system', description: 'Log damaged items.', status: 'idle', metric: '1', metricLabel: 'Reports Today', items: [{ label: 'Transit damage — Hoodie', value: 'Logged', status: 'warn' }] },
      { id: 'qc-9', name: 'Quality Control Analytics', type: 'analytics', description: 'Monitor product defect rates.', status: 'active', metric: '2.2%', metricLabel: 'Defect Rate', items: [{ label: 'Print Issues', value: '1.2%', status: 'good' }, { label: 'Fabric Issues', value: '0.6%', status: 'good' }, { label: 'Label Issues', value: '0.4%', status: 'good' }] },
      { id: 'qc-10', name: 'Shipment Protection Guidelines', type: 'library', description: 'Ensure safe packaging.', status: 'active', metric: '4', metricLabel: 'Guideline Sets', items: [{ label: 'Fragile Items', value: 'Bubble wrap + box' }, { label: 'Standard Apparel', value: 'Poly mailer' }, { label: 'Premium Orders', value: 'Custom box' }] },
      { id: 'qc-11', name: 'Brand Presentation Checklist', type: 'tracker', description: 'Maintain premium unboxing experience.', status: 'active', metric: '6', metricLabel: 'Check Points', items: [{ label: 'Tissue paper', value: 'Required' }, { label: 'Brand sticker', value: 'Required' }, { label: 'Thank you card', value: 'Required' }, { label: 'Promo insert', value: 'If available' }] },
      { id: 'qc-12', name: 'Packaging Workflow Manager', type: 'manager', description: 'Organize packing procedures.', status: 'active', metric: '3', metricLabel: 'Active Workflows', items: [{ label: 'Standard Flow', value: 'Active', status: 'good' }, { label: 'Premium Flow', value: 'Active', status: 'good' }, { label: 'Returns Flow', value: 'Active', status: 'good' }] },
      { id: 'qc-13', name: 'Product Return Inspection Tool', type: 'tracker', description: 'Inspect returned items.', status: 'active', metric: '6', metricLabel: 'Returns Pending', items: [{ label: 'Restockable', value: '4 items', status: 'good' }, { label: 'Damaged', value: '2 items', status: 'bad' }] },
      { id: 'qc-14', name: 'Packaging Training Resources', type: 'library', description: 'Teach new staff procedures.', status: 'active', metric: '8', metricLabel: 'Training Docs', items: [{ label: 'Onboarding Guide', value: 'Updated' }, { label: 'Video Tutorials', value: '4 videos' }, { label: 'Checklists', value: '3 docs' }] },
      { id: 'qc-15', name: 'Quality Assurance Reports', type: 'reports', description: 'Track quality performance.', status: 'active', metric: '4', metricLabel: 'Reports Available', items: [{ label: 'Weekly QC Report', value: 'Mar 5' }, { label: 'Defect Analysis', value: 'Mar 1' }, { label: 'Monthly Summary', value: 'Feb 28' }] },
    ],
  },
  {
    id: 'finance',
    title: 'Finance & Admin Coordinator',
    role: 'Finance',
    icon: '⬡',
    color: '#f97316',
    description: 'Tracks finances, expenses, and administrative tasks.',
    tools: [
      { id: 'fin-1', name: 'Financial Overview Dashboard', type: 'dashboard', description: 'View revenue and expenses.', status: 'active', metric: '$42.8K', metricLabel: 'Monthly Revenue', items: [{ label: 'Revenue', value: '$42,800', status: 'good' }, { label: 'Expenses', value: '$28,400' }, { label: 'Net Profit', value: '$14,400', status: 'good' }, { label: 'Margin', value: '33.6%', status: 'good' }] },
      { id: 'fin-2', name: 'Transaction Tracking System', type: 'tracker', description: 'Record company transactions.', status: 'active', metric: '342', metricLabel: 'This Month', items: [{ label: 'Sales', value: '286 transactions' }, { label: 'Expenses', value: '48 transactions' }, { label: 'Refunds', value: '8 transactions' }] },
      { id: 'fin-3', name: 'Expense Management Tool', type: 'manager', description: 'Track operational expenses.', status: 'active', metric: '$28.4K', metricLabel: 'Total Expenses', items: [{ label: 'Production', value: '$12,400', status: 'good' }, { label: 'Marketing', value: '$8,200' }, { label: 'Operations', value: '$4,600' }, { label: 'Staff', value: '$3,200' }] },
      { id: 'fin-4', name: 'Budget Planning Dashboard', type: 'monitor', description: 'Monitor spending limits.', status: 'active', metric: '72%', metricLabel: 'Budget Used', items: [{ label: 'Marketing', value: '68% used', status: 'good' }, { label: 'Production', value: '82% used', status: 'warn' }, { label: 'Operations', value: '64% used', status: 'good' }] },
      { id: 'fin-5', name: 'Payroll Management Panel', type: 'manager', description: 'Manage employee payments.', status: 'active', metric: '8', metricLabel: 'Team Members', items: [{ label: 'Next Payroll', value: 'Mar 15' }, { label: 'Total Payroll', value: '$18,400' }, { label: 'Pending Approval', value: '0', status: 'good' }] },
      { id: 'fin-6', name: 'Invoice Generator', type: 'builder', description: 'Create invoices for partners or clients.', status: 'active', metric: '12', metricLabel: 'Invoices (30d)', items: [{ label: 'Sent', value: '8', status: 'good' }, { label: 'Paid', value: '6', status: 'good' }, { label: 'Overdue', value: '2', status: 'bad' }] },
      { id: 'fin-7', name: 'Financial Reporting Center', type: 'reports', description: 'Generate financial summaries.', status: 'active', metric: '6', metricLabel: 'Reports', items: [{ label: 'P&L Statement', value: 'Feb 28' }, { label: 'Cash Flow', value: 'Mar 1' }, { label: 'Budget vs Actual', value: 'Mar 5' }] },
      { id: 'fin-8', name: 'Tax Document Storage', type: 'library', description: 'Store tax records securely.', status: 'active', metric: '24', metricLabel: 'Documents', items: [{ label: '2025 Returns', value: 'Filed', status: 'good' }, { label: '2026 Quarterly', value: 'Q1 Pending' }, { label: 'W-9 Forms', value: '8 on file' }] },
      { id: 'fin-9', name: 'Vendor Payment Tracker', type: 'tracker', description: 'Monitor payments to suppliers.', status: 'active', metric: '6', metricLabel: 'Pending Payments', items: [{ label: 'Fabric Supplier', value: '$4,200 — Due Mar 12', status: 'warn' }, { label: 'Print House', value: '$2,800 — Due Mar 18' }, { label: 'Packaging Co', value: '$1,400 — Paid', status: 'good' }] },
      { id: 'fin-10', name: 'Profit Margin Analyzer', type: 'analytics', description: 'Track brand profitability.', status: 'active', metric: '33.6%', metricLabel: 'Avg Margin', items: [{ label: 'Divergent', value: '38%', status: 'good' }, { label: 'Velvair', value: '34%', status: 'good' }, { label: 'Canjustalllove', value: '32%' }, { label: 'District88', value: '28%' }] },
      { id: 'fin-11', name: 'Subscription & Service Tracker', type: 'manager', description: 'Manage recurring expenses.', status: 'active', metric: '$2.4K', metricLabel: 'Monthly Subs', items: [{ label: 'Shopify', value: '$299/mo' }, { label: 'Adobe Suite', value: '$89/mo' }, { label: 'Cloudflare', value: '$25/mo' }, { label: 'Other', value: '$1,987/mo' }] },
      { id: 'fin-12', name: 'Cash Flow Monitor', type: 'monitor', description: 'Track company cash flow.', status: 'active', metric: '$62K', metricLabel: 'Cash Available', items: [{ label: 'Inflow (30d)', value: '$48,200', status: 'good' }, { label: 'Outflow (30d)', value: '$34,600' }, { label: 'Net Flow', value: '+$13,600', status: 'good' }] },
      { id: 'fin-13', name: 'Financial Forecast Tool', type: 'analytics', description: 'Project future revenue.', status: 'active', metric: '$156K', metricLabel: 'Q2 Forecast', items: [{ label: 'April', value: '$48K', status: 'good' }, { label: 'May', value: '$54K', status: 'good' }, { label: 'June', value: '$54K', status: 'good' }] },
      { id: 'fin-14', name: 'Budget Alerts System', type: 'system', description: 'Notify when spending limits approach.', status: 'alert', metric: '2', metricLabel: 'Active Alerts', items: [{ label: 'Production budget', value: '82% used', status: 'warn' }, { label: 'Marketing Q1', value: '90% used', status: 'bad' }] },
      { id: 'fin-15', name: 'Administrative Task Manager', type: 'manager', description: 'Track office and admin tasks.', status: 'active', metric: '8', metricLabel: 'Active Tasks', items: [{ label: 'File Q1 taxes', value: 'Due Mar 31', status: 'warn' }, { label: 'Update contracts', value: 'In Progress' }, { label: 'Insurance renewal', value: 'Due Apr 15' }] },
    ],
  },
]

export function getWorkspaceById(id: string) {
  return workspaces.find((w) => w.id === id)
}
